-- page_layout字段
UPDATE `page_layout_fields` SET `is_readonly` = '1' WHERE (`id` = 'f89ca48c-6b0d-46b1-919d-789013998b24');
UPDATE `page_layout_fields` SET `is_readonly` = '1' WHERE (`id` = '56a1718c-c838-11e7-ba58-186590dcd3c9');
UPDATE `page_layout_fields` SET `is_readonly` = '1' WHERE (`id` = '56a16f8f-c838-11e7-a16e-186590dcd3c9');

-- 新增编辑校验
INSERT INTO `object_validations` (`id`, `object_id`, `label`, `description`, `type`, `trigger_code`, `error_message`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `edit_type`, `is_active`, `source`, `name`) VALUES ('886c7579-d5da-11e8-a566-00059a3c7a00', '92f51257-c45a-11e7-8048-186590dcd3c9', '销售单元校验', '指标比例和销售比例加和为1校验', 'trigger', '\n\nfrom django.db.models import Sum\nfrom decimal import Decimal\nfrom orionbase.common import models\nfrom orionbase.common.orion_errors import create_validation_trigger_rule_errors\nobjects = models.SalesTerritories.objects.filter(deleted=0, sales_unit_id=instance.id).values(\'sales_unit_id\').annotate(\n    sum_target_ratio=Sum(\'target_ratio\'), sum_sales_ratio=Sum(\'sales_ratio\'))\n\ndecimal_1 = Decimal(\'1\')\nsum_target_ratio = [i[\'sales_unit_id\'] for i in objects if i[\'sum_target_ratio\'] != decimal_1]\nsum_sales_ratio = [i[\'sales_unit_id\'] for i in objects if i[\'sum_sales_ratio\'] != decimal_1]\nif sum_target_ratio and sum_sales_ratio:\n    raise create_validation_trigger_rule_errors(\n        u\'多岗位指标分配比例及销量分配比例加和应为1，请修改\')\nelif sum_target_ratio:\n    raise create_validation_trigger_rule_errors(\n        u\'多岗位指标分配比例加和应为1，请修改\')\nelif sum_sales_ratio:\n    raise create_validation_trigger_rule_errors(\n        u\'多岗位销量分配比例加和应为1，请修改\')\n    ', '', '0', '1', '2019-12-28 14:02:58', '1', '2020-01-14 16:58:46', 'post_save_page', '1', 'custom', 'sales_unit_post_save_page');
-- 导入校验
INSERT INTO `object_validations` (`id`, `object_id`, `label`, `description`, `type`, `trigger_code`, `error_message`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `edit_type`, `is_active`, `source`, `name`, `version`) VALUES ('71b52c61-7f0d-23fd-f43d-5cc5d4b571d2', 'f3707491-cdb5-11e7-ae05-186590dcd3c9', 'sales_territory_bulk', 'sales_territory_bulk_validation', 'trigger', 'from django.db.models import Sum\nfrom orionbase.common.models import SalesUnits\nfrom django.db import connection\nfrom django.db.models import Sum\nerror_dict = {}\ntarget_ratio_error_list = []\nsales_ratio_error_list = []\n\nobjects = objects.filter(deleted=0).values(\'sales_unit_id\').annotate(\n    sum_target_ratio=Sum(\'target_ratio\'), sum_sales_ratio=Sum(\'sales_ratio\'))\nsum_target_ratio = [i[\'sales_unit_id\'] for i in objects if i[\'sum_target_ratio\'] != 1]\nsum_sales_ratio = [i[\'sales_unit_id\'] for i in objects if i[\'sum_sales_ratio\'] != 1]\nif sum_target_ratio:\n    target_ratio_error_list = list(SalesUnits.advance_objects.filter(\n        id__in=sum_target_ratio).values_list(\'account_id\', \'package_id\', \'yearmonth\'))\nif sum_sales_ratio:\n    sales_ratio_error_list = list(SalesUnits.advance_objects.filter(\n        id__in=sum_sales_ratio).values_list(\'account_id\', \'package_id\', \'yearmonth\'))\n\nif target_ratio_error_list or sales_ratio_error_list:\n    error_dict[u\'指标分配比例加和不等于1;\'] = target_ratio_error_list\n    error_dict[u\'销量分配比例加和不等于1;\'] = sales_ratio_error_list\n    raise create_validation_trigger_rule_errors(error_dict)', '', '0', '1', '2019-06-24 11:07:18', '1', '2019-06-24 11:07:18', 'bulk_post_save', '1', 'custom', 'sales_territory_import', '1');
