-- 添加岗位级：产品经理
INSERT INTO `picklist_values`(`id`, `picklist_id`, `name`, `label`, `order`, `description`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `source`, `depending_on`) VALUES ('e30fda45-5658-11e7-9202-784f43941804', '34acb3de-3933-11e7-9b77-784f43949f5b', 'position_level_17', '产品经理', 9, '产品经理', 0, 1, '2020-08-29 22:50:21', 1, '2017-05-15 16:00:00', 'custom', NULL);

-- 更新日程配置
UPDATE`custom_settings` SET `deleted` = 0, `created_on` = '2020-02-05 07:31:40.655174', `modified_on` = '2020-02-05 07:31:40.655270', `key` = 'calendar_display_mode_setting', `value` = '{\r\n	\"enable_weekly_plan\": true,\r\n	\"enable_differential_display\": true,\r\n	\"call_state_to_be_compared\": [],\r\n	\"tot_state_to_be_compared\": [],\r\n	\"tot_type_mapping\": {\r\n		\"tot_type_id\": \"weekly_plan__tot_id\"\r\n	},\r\n	\"enable_call_finish_action\": true,\r\n	\"enable_coaching_finish_action\": true,\r\n	\"enable_allow_adjust\": false,\r\n	\"calendar_timeline\": {\r\n		\"every_day_range_time\": {\r\n			\"am\": [\r\n				\"07:00:00\",\r\n				\"12:00:00\"\r\n			],\r\n			\"pm\": [\r\n				\"12:00:00\",\r\n				\"19:00:00\"\r\n			]\r\n		},\r\n		\"unknown_max_minutes\": 30,\r\n		\"objects\": {\r\n			\"time_off_territory\": {\r\n				\"__default__\": {\r\n					\"values\": {\r\n						\"am\": [\r\n							\"forenoon\"\r\n						],\r\n						\"pm\": [\r\n							\"afternoon\"\r\n						]\r\n					},\r\n					\"column_names\": [\r\n						\"date\",\r\n						\"ampm\"\r\n					],\r\n					\"type\": \"full\"\r\n				}\r\n			},\r\n			\"coaching\": {\r\n				\"__default__\": {\r\n					\"column_names\": [\r\n						\"coaching_date\"\r\n					],\r\n					\"type\": \"date\"\r\n				}\r\n			},\r\n			\"call\": {\r\n				\"__default__\": {\r\n					\"column_names\": [\r\n						\"call_date\"\r\n					],\r\n					\"type\": \"date\"\r\n				}\r\n			},\r\n			\"event\": {\r\n				\"__default__\": {\r\n					\"column_names\": [\r\n						\"event_start_time\",\r\n						\"event_end_time\"\r\n					],\r\n					\"type\": \"range\"\r\n				}\r\n			},\r\n			\"weekly_plan\": {\r\n				\"__default__\": {\r\n					\"values\": {\r\n						\"am\": [\r\n							\"am\"\r\n						],\r\n						\"pm\": [\r\n							\"pm\"\r\n						]\r\n					},\r\n					\"column_names\": [\r\n						\"date\",\r\n						\"ampm\"\r\n					],\r\n					\"type\": \"ampm\"\r\n				},\r\n				\"weekly_plan_coaching_plans\": {\r\n					\"column_names\": [\r\n						\"date\"\r\n					],\r\n					\"type\": \"date\"\r\n				},\r\n				\"time_off_territory\": {\r\n					\"type\": \"full\",\r\n					\"column_names\": [\r\n						\"date\",\r\n						\"ampm\"\r\n					],\r\n					\"values\": {\r\n						\"am\": [\r\n							\"am\"\r\n						],\r\n						\"pm\": [\r\n							\"pm\"\r\n						]\r\n					}\r\n				}\r\n			}\r\n		}\r\n	}\r\n}', `created_by` = 1, `modified_by` = 1, `position_id` = NULL, `description` = '日程显示方式设置', `type` = 'json', `module_id` = 'schedule' WHERE `id` = 95;
UPDATE `custom_settings` SET `deleted` = 0, `created_on` = '2020-08-17 07:23:51.746858', `modified_on` = '2020-08-17 07:23:51.746918', `key` = 'calendar_create_data_config', `value` = '[\r\n	{\r\n		\"fields\": [\r\n			{\r\n				\"type\": \"date\",\r\n				\"name\": \"call_date\"\r\n			}\r\n		],\r\n		\"object_name\": \"call\"\r\n	},\r\n	{\r\n		\"fields\": [\r\n			{\r\n				\"type\": \"date\",\r\n				\"name\": \"coaching_date\"\r\n			}\r\n		],\r\n		\"object_name\": \"coaching\"\r\n	},\r\n	{\r\n		\"fields\": [\r\n			{\r\n				\"type\": \"datetime\",\r\n				\"name\": \"event_start_time\",\r\n				\"time_tag\": \"start\"\r\n			},\r\n			{\r\n				\"type\": \"datetime\",\r\n				\"name\": \"event_end_time\",\r\n				\"time_tag\": \"end\"\r\n			}\r\n		],\r\n		\"record_type_config\": {\r\n			\"cs_patient_education_meeting\": {\r\n				\"fields_for_agenda\": [],\r\n				\"fields_for_plan\": [\r\n					{\r\n						\"type\": \"datetime\",\r\n						\"name\": \"event_start_time\",\r\n						\"time_tag\": \"start\"\r\n					},\r\n					{\r\n						\"type\": \"datetime\",\r\n						\"name\": \"end_time\",\r\n						\"time_tag\": \"end\"\r\n					}\r\n				]\r\n			},\r\n			\"cs_department\": {\r\n				\"fields_for_agenda\": []\r\n			}\r\n		},\r\n		\"object_name\": \"event\"\r\n	},\r\n	{\r\n		\"fields\": [\r\n			{\"type\":\"date\",\"name\":\"coaching_date\"}\r\n		],\r\n		\"record_type_config\": {\r\n			\"weekly_plan_call_plans\": {\r\n				\"fields_for_agenda\": [],\r\n				\"fields_for_plan\": [\r\n					{\r\n				\"type\": \"date\",\r\n				\"name\": \"coaching_date\"\r\n			}\r\n				]\r\n			 },\r\n			\"weekly_plan_coaching_plans\": {\r\n				\"fields_for_agenda\": [],\r\n				\"fields_for_plan\": [{\"type\":\"date\",\"name\":\"coaching_date\"}]\r\n			 }\r\n			},\r\n		\"object_name\": \"weekly_plan\"\r\n	},\r\n	{\r\n		\"fields\": [\r\n			{\r\n				\"type\": \"date\",\r\n				\"name\": \"date\"\r\n			}\r\n		],\r\n		\"object_name\": \"time_off_territory\"\r\n	}\r\n]', `created_by` = 1, `modified_by` = 1, `position_id` = NULL, `description` = '新建日程配置', `type` = 'json', `module_id` = 'schedule' WHERE `id` = 120;


-- 添加去完成按钮的显示逻辑
UPDATE `object_actions` SET `visibility_setting_ps` = 1 WHERE `id` = '4ac15c6d-02f4-11eb-bc49-0215c63fce1a';
