-- 协办人可以看见所有人添加参会人权限
UPDATE `custom_settings` SET `value`='{\"allow_share_user_view_attendees\": true, \"allow_share_user_view_HCOs\": true,\"allow_sorting_instead_owner\":true}' WHERE `id`='70';


-- 其他参会人的扫码签到时的 layout
INSERT INTO `page_layouts` (`id`, `page_id`, `name`, `label`, `source`, `screen_size`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`) VALUES ('bd619b2d-96b0-42a5-843e-5b30d53b3fe9', '08d05c00-197c-40e5-9920-a65e3daf7a7c', 'event_professional_sign_in_form', '医生其他参会人报名表单填写', 'custom', 'both', '0', '1', '2018-05-09 03:28:41', '1', '2018-05-09 03:28:41');

INSERT INTO `page_layout_fields` (`id`, `page_layout_id`, `type`, `object_field_id`, `label`, `order`, `colspan`, `is_mandatory`, `is_readonly`, `display_mode`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `is_header`) VALUES ('5da825d3-26ff-4471-9677-e4a45ea1c90f', 'bd619b2d-96b0-42a5-843e-5b30d53b3fe9', 'field', 'b475716c-e510-4574-a8b2-c86804825e75', '医院', '2', '6', '1', '0', 'both', '0', '1', '2018-05-09 03:28:41', '1', '2018-05-09 03:28:41', '0');
INSERT INTO `page_layout_fields` (`id`, `page_layout_id`, `type`, `object_field_id`, `label`, `order`, `colspan`, `is_mandatory`, `is_readonly`, `display_mode`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `is_header`) VALUES ('6fc388d4-0a1f-42d5-9e92-eedc92a4ac91', 'bd619b2d-96b0-42a5-843e-5b30d53b3fe9', 'field', 'acf79a64-e386-4b7a-9ce2-f51c8924cdf9', '科室', '1', '6', '1', '0', 'both', '0', '1', '2018-05-09 03:28:41', '1', '2018-05-09 03:28:41', '0');
INSERT INTO `page_layout_fields` (`id`, `page_layout_id`, `type`, `object_field_id`, `label`, `order`, `colspan`, `is_mandatory`, `is_readonly`, `display_mode`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `is_header`) VALUES ('df8e4c12-740d-469c-83fa-165cf623d4c6', 'bd619b2d-96b0-42a5-843e-5b30d53b3fe9', 'field', 'c43d4e09-e16e-421a-a020-a00a1dd99404', '姓名', '0', '6', '1', '1', 'both', '0', '1', '2018-05-09 03:28:41', '1', '2018-05-09 03:28:41', '0');
INSERT INTO `page_layout_fields` (`id`, `page_layout_id`, `type`, `object_field_id`, `label`, `order`, `colspan`, `is_mandatory`, `is_readonly`, `display_mode`, `deleted`, `created_by`, `created_on`, `modified_by`, `modified_on`, `is_header`) VALUES ('783de09d-7fa3-11ea-aab5-0215c63fce1a', 'bd619b2d-96b0-42a5-843e-5b30d53b3fe9', 'field', 'dda76ce6-abb2-45e3-9702-3b4cd97e890f', '手机号', '3', '6', '1', '1', 'both', '0', '1', '2018-05-09 03:28:41', '1', '2018-05-09 03:28:41', '0');

-- 报告草稿阶段 增加 不需分拣按钮
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = '7f1879dd-7f0c-419e-a56b-688afdf3ea57');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = 'bdab4e95-285b-4fa3-a8c3-7078fb69378a');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = 'fb317194-f02c-43b3-8aa5-a772b529dbca');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = '90cff43a-1a03-45de-bbaf-d9dbe035a2be');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = '69d6af46-f37a-4ab2-941a-eb79453845f0');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = '3178b4cd-880f-47f1-8b9c-bb167d46d810');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = 'c09a0dbf-2a8c-4f0a-b71b-278c926e0452');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = 'fdcb46e7-f752-4fbd-8b9c-6fdec0029f1f');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = 'd813b15f-56bd-44ed-a7e2-c8a1b9e711b5');
UPDATE `page_layout_tabs` SET `configurations` = '{\"enable_check_in\": true, \"show_only_my_attendee\": false, \"enable_walk_in\": true, \"enable_check_in_button\": true, \"enable_electric_invitation_button\": false, \"enable_tencent_state_display\": true, \"enable_electric_invitation\": false, \"one_click_send_document\": false, \"display_document_send_status\": false, \"one_click_send_invitation\": false, \"display_invitation_send_status\": true, \"one_click_send_survey\": false, \"display_survey_send_status\": false,\"enable_attendee_add\":true,\"enable_professional_sorting\":true,\"enable_refuse_sorting\":true}' WHERE (`id` = '1376f179-433a-4924-a46b-0b2a0d2d445f');
